{
    parserClass="org.intellij.sdk.language.parser.McFunctionParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="McFunction"
    psiImplClassSuffix="Impl"
    psiPackage="org.intellij.sdk.language.psi"
    psiImplPackage="org.intellij.sdk.language.psi.impl"

    elementTypeHolderClass="org.jonatjano.mclang.psi.McFunctionTypes"
    elementTypeClass="org.jonatjano.mclang.psi.McFunctionElementType"
    tokenTypeClass="org.jonatjano.mclang.psi.McFunctionTokenType"

}
//simpleFile ::= item_*
//
//private item_ ::= (property|COMMENT|CRLF)
//
//property ::= (KEY? SEPARATOR VALUE?) | KEY

mcFunctionFile ::= item_*

private item_ ::= (command|COMMENT|CRLF)

command ::= (killCommand|tpCommand)
entities ::= (ENTITY|MULTI_ENTITY)

killCommand ::= KILL entities

tpCommand ::= TELEPORT ((entities ENTITY)|(entities tpVecArgs)|ENTITY|tpVecArgs)
tpVecArgs ::= VEC3 (ROTATION|tpFacingArg)?
tpFacingArg ::= TOK_FACING (VEC3|(TOK_ENTITY ENTITY)) ENTITY_ANCHOR?
